### PR TITLE
Rename DataFlowTasks.@spawn to @dspawn, export it

### LINKED ISSUE #68: Revert to DataFlowTasks.@dspawn
For v0.2:
- revert to `@dspawn` instead of `@spawn`
- export `@dspawn`

### PR DESCRIPTION
**Pull request by ffevotte**
Closes: #68

### CODE REVIEW

**Comment by ffevotte** [comment]
Documentation preview: https://maltezfaria.github.io/DataFlowTasks.jl/previews/PR69/

**Comment by ffevotte** [comment]
I took the liberty of making the relevant changes in https://github.com/maltezfaria/TiledFactorization

**Comment by ffevotte** [comment]
I went through the docs, and everything seemed OK. But even though all tests pass, maybe we want to be extra careful with such changes and double-check that everything is consistent.

**Comment by maltezfaria** [comment]
LGTM

**Pull request merged**
